from enum import IntEnum, auto

class Activity(IntEnum):
    Invalid = -1

    Transition = auto()

    Stand = auto()
    Run = auto()
    Crouch = auto()
    Crouch_Walk = auto()
    Swim = auto()
    Air_Walk = auto()
    Jump = auto()
    Jump_Start = auto()
    Jump_Float = auto()
    Jump_Land = auto()
    Double_Jump_Crouch = auto()

    Attack_Stand = auto()
    Attack_Crouch = auto()
    Attack_Swim = auto()
    Attack_Air_Walk = auto()

    Reload_Stand = auto()
    Reload_Stand_Loop = auto()
    Reload_Stand_End = auto()
    Reload_Crouch = auto()
    Reload_Crouch_Loop = auto()
    Reload_Crouch_End = auto()
    Reload_Swim = auto()
    Reload_Swim_Loop = auto()
    Reload_Swim_End = auto()
    Reload_Air_Walk = auto()
    Reload_Air_Walk_Loop = auto()
    Reload_Air_Walk_End = auto()

    Gesture_Flinch = auto()
    Gesture_VC_Hand_Mouth = auto()
    Gesture_VC_Finger_Point = auto()
    Gesture_VC_Fist_Pump = auto()
    Gesture_VC_Thumbs_Up = auto()
    Gesture_VC_Nod_Yes = auto()
    Gesture_VC_Nod_No = auto()

    Primary_Stand = auto()
    Primary_Run = auto()
    Primary_Crouch = auto()
    Primary_Crouch_Walk = auto()
    Primary_Swim = auto()
    Primary_Air_Walk = auto()
    Primary_Jump = auto()
    Primary_Jump_Start = auto()
    Primary_Jump_Float = auto()
    Primary_Jump_Land = auto()
    Primary_Double_Jump_Crouch = auto()

    Primary_Attack_Stand = auto()
    Primary_Attack_Crouch = auto()
    Primary_Attack_Swim = auto()
    Primary_Attack_Air_Walk = auto()

    Primary_Reload_Stand = auto()
    Primary_Reload_Stand_Loop = auto()
    Primary_Reload_Stand_End = auto()
    Primary_Reload_Crouch = auto()
    Primary_Reload_Crouch_Loop = auto()
    Primary_Reload_Crouch_End = auto()
    Primary_Reload_Swim = auto()
    Primary_Reload_Swim_Loop = auto()
    Primary_Reload_Swim_End = auto()
    Primary_Reload_Air_Walk = auto()
    Primary_Reload_Air_Walk_Loop = auto()
    Primary_Reload_Air_Walk_End = auto()

    Primary_Gesture_Flinch = auto()
    Primary_Gesture_VC_Hand_Mouth = auto()
    Primary_Gesture_VC_Finger_Point = auto()
    Primary_Gesture_VC_Fist_Pump = auto()
    Primary_Gesture_VC_Thumbs_Up = auto()
    Primary_Gesture_VC_Nod_Yes = auto()
    Primary_Gesture_VC_Nod_No = auto()

    Secondary_Stand = auto()
    Secondary_Run = auto()
    Secondary_Crouch = auto()
    Secondary_Crouch_Walk = auto()
    Secondary_Swim = auto()
    Secondary_Air_Walk = auto()
    Secondary_Jump = auto()
    Secondary_Jump_Start = auto()
    Secondary_Jump_Float = auto()
    Secondary_Jump_Land = auto()
    Secondary_Double_Jump_Crouch = auto()

    Secondary_Attack_Stand = auto()
    Secondary_Attack_Crouch = auto()
    Secondary_Attack_Swim = auto()
    Secondary_Attack_Air_Walk = auto()

    Secondary_Reload_Stand = auto()
    Secondary_Reload_Stand_Loop = auto()
    Secondary_Reload_Stand_End = auto()
    Secondary_Reload_Crouch = auto()
    Secondary_Reload_Crouch_Loop = auto()
    Secondary_Reload_Crouch_End = auto()
    Secondary_Reload_Swim = auto()
    Secondary_Reload_Swim_Loop = auto()
    Secondary_Reload_Swim_End = auto()
    Secondary_Reload_Air_Walk = auto()
    Secondary_Reload_Air_Walk_Loop = auto()
    Secondary_Reload_Air_Walk_End = auto()

    Secondary_Gesture_Flinch = auto()
    Secondary_Gesture_VC_Hand_Mouth = auto()
    Secondary_Gesture_VC_Finger_Point = auto()
    Secondary_Gesture_VC_Fist_Pump = auto()
    Secondary_Gesture_VC_Thumbs_Up = auto()
    Secondary_Gesture_VC_Nod_Yes = auto()
    Secondary_Gesture_VC_Nod_No = auto()

    Melee_Stand = auto()
    Melee_Run = auto()
    Melee_Crouch = auto()
    Melee_Crouch_Walk = auto()
    Melee_Swim = auto()
    Melee_Air_Walk = auto()
    Melee_Jump = auto()
    Melee_Jump_Start = auto()
    Melee_Jump_Float = auto()
    Melee_Jump_Land = auto()
    Melee_Double_Jump_Crouch = auto()

    Melee_Attack_Stand = auto()
    Melee_Attack_Crouch = auto()
    Melee_Attack_Swim = auto()
    Melee_Attack_Air_Walk = auto()

    Melee_Gesture_Flinch = auto()
    Melee_Gesture_VC_Hand_Mouth = auto()
    Melee_Gesture_VC_Finger_Point = auto()
    Melee_Gesture_VC_Fist_Pump = auto()
    Melee_Gesture_VC_Thumbs_Up = auto()
    Melee_Gesture_VC_Nod_Yes = auto()
    Melee_Gesture_VC_Nod_No = auto()

    VM_Draw = auto()
    VM_Idle = auto()
    VM_Fire = auto()
    VM_Reload = auto()
    VM_Reload_Start = auto()
    VM_Reload_Finish = auto()

    Primary_VM_Idle = auto()
    Primary_VM_Draw = auto()
    Primary_VM_Fire = auto()
    Primary_VM_Reload_Start = auto()
    Primary_VM_Reload = auto()
    Primary_VM_Reload_End = auto()

    Secondary_VM_Idle = auto()
    Secondary_VM_Draw = auto()
    Secondary_VM_Fire = auto()
    Secondary_VM_Reload_Start = auto()
    Secondary_VM_Reload = auto()
    Secondary_VM_Reload_End = auto()

    Melee_VM_Idle = auto()
    Melee_VM_Draw = auto()
    Melee_VM_Swing = auto()

    Taunt = auto()
